// <auto-generated />
namespace Notlarim101.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EntityEkleme : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EntityEkleme));
        
        string IMigrationMetadata.Id
        {
            get { return "202112240924548_EntityEkleme"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
